dist: xenial
language: python

cache: pip
before_install:
  - pip install --upgrade pip
install:
  - pip install tox
  - pip install coveralls
script:
  - tox
after_success:
  - coveralls

jobs:
  include:
    - python: '2.7'
      env: TOXENV=py27-dj111
    - python: '3.4'
      env: TOXENV=py34-dj111
    - python: '3.5'
      env: TOXENV=py35-dj111
    - python: '3.6'
      env: TOXENV=py36-dj111
    - python: '3.6'
      env: TOXENV=lint

    - stage: release
      python: '3.6'
      if: tag IS present
      deploy:
        provider: pypi
        user: Praekelt
        password:
          secure: O0feip8iJtd8Pulu2m9qcAg2yqwBUe5FsvYSaWTJke8a9oiS4xGittATKqbxUZNvFjHpbS79V2032IPDs+oNePwotSavPiKeSF1xNxAaeGuEH7nFuaYQ4/RzLpHHYU3KT61sa32U+bdH3AoDvAb/5MzlLucTVGLEuCUpHXLhcx0=
        distributions: sdist bdist_wheel
        on: {tags: true}

      install: skip
      script: skip
